name: darts
favicon: null
layout_spectrum: 0.23206
typography_spectrum: 0.05328
title: 'Darts Hub on the grid!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#007020'
    - '#78B088'
    - '#C02028'
    - '#000000'
  brandStrength: 0.811207
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
